"""Generate docs/reference/config.md from the lgtmaybe pydantic schemas.

Run with:
    uv run python docs/generate_reference.py

The output is deterministic (stable key ordering) so CI can detect drift with a
byte-for-byte comparison.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from lgtmaybe.core.models import (
    PRContext,
    Provider,
    ProviderResult,
    ReviewConfig,
    ReviewFinding,
    Severity,
)

OUTPUT_PATH = Path(__file__).parent / "reference" / "config.md"

BANNER = """\
<!-- DO NOT EDIT — this file is generated by docs/generate_reference.py.
     Run `uv run python docs/generate_reference.py` to regenerate.
     CI will fail if this file is stale. -->
"""


def _type_label(prop: dict[str, Any], defs: dict[str, Any]) -> str:
    """Return a human-readable type string for a JSON Schema property."""
    if "$ref" in prop:
        ref_name: str = str(prop["$ref"]).split("/")[-1]
        ref = defs.get(ref_name, {})
        if "enum" in ref:
            # Use slashes so the type cell doesn't break the markdown table.
            values = " / ".join(f"`{v}`" for v in sorted(ref["enum"]))
            return values
        return ref_name

    type_map = {
        "string": "string",
        "integer": "integer",
        "number": "number",
        "boolean": "boolean",
        "array": "list",
        "object": "object",
    }
    json_type = prop.get("type", "")
    if json_type == "array":
        items = prop.get("items", {})
        inner = _type_label(items, defs)
        return f"list[{inner}]"
    if "anyOf" in prop:
        parts = [_type_label(p, defs) for p in prop["anyOf"] if p != {"type": "null"}]
        label = " / ".join(parts)
        if any(p == {"type": "null"} for p in prop["anyOf"]):
            label += " / null"
        return label
    return type_map.get(json_type, json_type or "any")


def _default_label(prop: dict[str, Any], *, is_required: bool) -> str:
    """Return a markdown-friendly default value string, or '—' if required."""
    if "default" not in prop:
        # Pydantic omits the default key for list fields using default_factory=list.
        if not is_required and prop.get("type") == "array":
            return "`[]`"
        return "—"
    default = prop["default"]
    if isinstance(default, list) and len(default) == 0:
        return "`[]`"
    if default is None:
        return "`null`"
    return f"`{default}`"


def _render_schema_table(schema: dict[str, Any]) -> str:
    """Render a markdown table for the properties of one pydantic model."""
    defs = schema.get("$defs", {})
    properties = schema.get("properties", {})
    required_fields = set(schema.get("required", []))

    rows: list[str] = []
    rows.append("| Field | Type | Required | Default | Description |")
    rows.append("|---|---|---|---|---|")

    for name in sorted(properties.keys()):
        prop = properties[name]
        type_label = _type_label(prop, defs)
        required = "Yes" if name in required_fields else "No"
        default = _default_label(prop, is_required=name in required_fields)
        description = prop.get("description") or prop.get("title") or ""
        rows.append(f"| `{name}` | {type_label} | {required} | {default} | {description} |")

    return "\n".join(rows)


def _enum_section(name: str, members: list[str], description: str) -> str:
    values = "\n".join(f"- `{m}`" for m in sorted(members))
    return f"### {name}\n\n{description}\n\n{values}\n"


def generate() -> str:
    """Return the full content of config.md as a string."""
    review_config_schema = ReviewConfig.model_json_schema()
    review_finding_schema = ReviewFinding.model_json_schema()
    provider_result_schema = ProviderResult.model_json_schema()
    pr_context_schema = PRContext.model_json_schema()

    sections: list[str] = [
        BANNER,
        "# Configuration Reference\n",
        "This reference is generated from the pydantic schemas in `src/lgtmaybe/core/models.py`.\n",
    ]

    # ReviewConfig
    sections.append("## ReviewConfig\n")
    sections.append(
        "The user-facing configuration model. Fields map directly to `.lgtmaybe.yml` keys "
        "and CLI flags.\n"
    )
    sections.append(_render_schema_table(review_config_schema))
    sections.append("")

    # Enums
    sections.append("## Enums\n")
    sections.append(
        _enum_section(
            "Provider",
            [p.value for p in Provider],
            "LLM backend selected by `--provider`. "
            "Cloud providers (`bedrock`, `vertex`) use ambient credentials; "
            "`azure` uses an API key plus the resource endpoint (`--api-base`).",
        )
    )
    sections.append(
        _enum_section(
            "Severity",
            [s.value for s in Severity],
            "Finding severity, ordered low to high. "
            "Use `min_severity` in config to suppress findings below a threshold.",
        )
    )

    # ReviewFinding
    sections.append("## ReviewFinding\n")
    sections.append(
        "The structured output the model must return for each inline comment. "
        "All fields are validated by pydantic before anything is posted to GitHub.\n"
    )
    sections.append(_render_schema_table(review_finding_schema))
    sections.append("")

    # ProviderResult
    sections.append("## ProviderResult\n")
    sections.append(
        "The normalised return value of one LLM completion, including usage and cost.\n"
    )
    sections.append(_render_schema_table(provider_result_schema))
    sections.append("")

    # PRContext
    sections.append("## PRContext\n")
    sections.append(
        "Everything the engine needs about a pull request. "
        "Fetched via the GitHub REST API — PR code is never checked out.\n"
    )
    sections.append(_render_schema_table(pr_context_schema))
    sections.append("")

    # Raw schemas
    sections.append("## Raw JSON schemas\n")
    sections.append(
        "The canonical machine-readable schemas. These are the source of truth for "
        "provider output validation.\n"
    )
    for label, schema in [
        ("ReviewConfig", review_config_schema),
        ("ReviewFinding", review_finding_schema),
        ("ProviderResult", provider_result_schema),
        ("PRContext", pr_context_schema),
    ]:
        sections.append(f"### {label}\n")
        sections.append(f"```json\n{json.dumps(schema, indent=2, sort_keys=True)}\n```\n")

    return "\n".join(sections)


def main() -> None:
    content = generate()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Written: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
